-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "purchaseDate" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "creationDate" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
